on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          project: '.'
      - uses: julia-actions/cache@v2

      - run: pwd
      - run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: ./lectures/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
